### ISSUE TITLE
i18n document

### ISSUE THREAD

**Issue by SamYuan1990** [hyperledger-labs/PerformanceSandBox#16]
### Is your proposal related to a problem?

No

### Describe the solution you'd like

i18n document

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by sheetalj2205** [comment]
Hello @SamYuan1990,  Can you please assign this issue to me ? This would be my first contribution to hyperledger as a beginner so I want to start it with a issue related to documentation.

**Comment by sheetalj2205** [comment]
Thanks @SamYuan1990 for assigning this to me. Can you please add more description about this issue as it is not descriptive enough?

**Comment by SamYuan1990** [comment]
@sheetalj2205 , you know i18n is short for internationalization and localization.
you are free to translate current document with any other language you like.

**Comment by sheetalj2205** [comment]
Thanks for informing @SamYuan1990 . Is this mean that I need to convert entire doc folder of the repository in any other language?

**Comment by SamYuan1990** [comment]
> [Thanks for informing @SamYuan1990 . does this mean that I need to convert entire doc folder of the repository in any other language?
> 
> I am thinking to solve this issue with following steps:
> 
> 1. First fork and clone the repository.
> 2. Create a separate branch with name [new-feature#issue-number], using vs code as a editor.
> 3. Create a folder docs/locale to translate the current doc folder into local language like chinese, then create a folder zh_CN in the docs/locale folder to add all the .md files in it by translating them into chinese.
> 4. Commit changes and create a pull request.
> 
> Can you please tell me whether am I on the right track for solving this issue or not?

yes, you are correct.

**Comment by sheetalj2205** [comment]
> > [Thanks for informing @SamYuan1990 . does this mean that I need to convert entire doc folder of the repository in any other language?
> > I am thinking to solve this issue with following steps:
> > 
> > 1. First fork and clone the repository.
> > 2. Create a separate branch with name [new-feature#issue-number], using vs code as a editor.
> > 3. Create a folder docs/locale to translate the current doc folder into local language like chinese, then create a folder zh_CN in the docs/locale folder to add all the .md files in it by translating them into chinese.
> > 4. Commit changes and create a pull request.
> > 
> > Can you please tell me whether am I on the right track for solving this issue or not?
> 
> yes, you are correct.

Thanks for replying @SamYuan1990 . Can I create this PR on 16th March as I have continuously exams from tomorrow till 16th. I hope you'll consider this.

**Comment by sheetalj2205** [comment]
@SamYuan1990 can you please tell me where are all files of the doc folder now? I guess there are some changes that have been made.
