### ISSUE TITLE
FAQ page

### ISSUE THREAD

**Issue by SamYuan1990** [hyperledger-labs/PerformanceSandBox#25]
1. may I able to use my own image?
2. may I able to use my own k8s?
3. may I able to use my own SUT?
4. different with running caliper with monitoring?

**Comment by sheetalj2205** [comment]
Hello @SamYuan1990 . I want to work on this issue but can you please help me with the answers so that I would be able to create a FAQ page?

**Comment by SamYuan1990** [comment]
> Hello @SamYuan1990 . I want to work on this issue but can you please help me with the answers so that I would be able to create a FAQ page?

thanks, @sheetalj2205 , but I will create it myself with existing questions and answers.

**Comment by SamYuan1990** [comment]
https://github.com/hyperledger-labs/PerformanceSandBox/wiki/FAQ
