### ISSUE TITLE
Add CI for this project

### ISSUE THREAD

**Issue by SamYuan1990** [hyperledger-labs/PerformanceSandBox#33]
### Is your proposal related to a problem?

N/A

### Describe the solution you'd like

Ref to https://github.com/hyperledger/fabric-samples we'd better to have a CI to ensure our code able to run.

### Describe alternatives you've considered

So far not 

### Additional context

N/A

**Comment by tkuhrt** [comment]
@ryjones is probably best suited to help with the CI question that you have @SamYuan1990 

> @tkuhrt , may I know if I want to enable CI as github flow or azp for this repo, what should I do? code for CI, as pipeline as code. and?

**Comment by ryjones** [comment]
@SamYuan1990 there are no restrictions on GitHub actions - you can just set them up and use them.

**Comment by SamYuan1990** [comment]
I will have a try and keep you feedback @ryjones
